# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
#Importar numpy
import numpy as np

In [3]:
# Ejercicio 1. Crear un arreglo de ceros de longitud 12
print(np.zeros(12))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
#Ejercicio 2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
arreglo = np.zeros(10)
arreglo[5]= 10
print(arreglo)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [24]:
#Ejercicio 3. Crear un arreglo que tenga los números del 10 al 49
print(np.arange(10,50,1))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [28]:
#Ejercicio 4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
lista = [[0,1,2],[3,4,5],[6,7,8]]
array2 = np.array(lista)
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
#Ejercicio 5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
array3 = np.random.rand(100)#Con distribución de probabilidades uniforme
print(array3)

[5.82831776e-01 2.94053899e-01 9.41993324e-02 1.77682139e-01
 2.86149177e-01 5.04439478e-02 3.17175468e-02 9.88009191e-01
 6.34910901e-01 6.28397670e-01 1.83769288e-01 6.62958815e-01
 1.30832174e-01 9.00072655e-01 9.55396611e-01 8.72336610e-01
 1.34543573e-04 9.71595020e-01 2.81685679e-01 4.94067026e-01
 3.45423048e-02 3.69351295e-02 4.20888285e-01 2.72098600e-01
 3.27350574e-01 4.19541928e-01 3.40274984e-01 9.48881608e-01
 5.06552166e-01 9.82501704e-01 2.45912163e-01 3.37062282e-01
 1.53272350e-01 7.47170074e-01 8.60288650e-01 4.37971061e-01
 6.19603107e-01 4.71703798e-01 4.43224300e-01 7.15633572e-01
 5.54621377e-01 1.57218493e-01 4.63672584e-01 8.78742047e-01
 8.79703263e-01 3.53528685e-01 1.07893474e-02 9.55283686e-01
 2.05950881e-01 4.42890052e-01 9.82242128e-01 6.70449200e-01
 6.24032074e-01 1.71616062e-01 2.52466591e-01 2.57506290e-01
 5.90163609e-01 4.47544386e-03 5.37131664e-01 8.67088469e-01
 8.46886195e-01 8.24531111e-01 8.45629474e-01 2.39362695e-02
 4.96214215e-02 9.139228

In [62]:
f"La media es: {round(np.mean(array3),3)}"

'La media es: 0.503'

In [63]:
f"La varianza es: {round(np.var(array3),3)}"

'La varianza es: 0.091'

In [59]:
#Ejercicio 6. Calcular la media de un arreglo usando np.sum
np.sum(array3)/len(array3)

0.5031650479713501

In [56]:
#Ejercicio 7. Calcular la varianza de un arreglo usando np.sum y np.mean
lista1 = []
conteo =0
for i in array3:
    dif= (i-np.mean(array3))**2
    lista1.append(dif)
    conteo+=1
df = len(array3)-1
print(np.sum(np.array(lista1))/df)


0.09156473408492594


In [60]:
#Otra opción sin np.sum
suma=0
for i in array3:
    dif= (i-np.mean(array3))**2
    df = len(array3)-1
    suma += dif
print(suma/df)

0.09156473408492596


In [66]:
#Ejercicio 8. Crear un array de números aleatorios usando np.random.randn.
array4 = np.random.randn(50)
print(array4)

[ 0.78177812 -0.36700988 -0.96764756  1.15347247 -1.50155836  0.61919296
  1.75758513 -1.4912395  -2.0740913  -0.72368954 -0.46895437  0.30071037
  1.15273932 -1.47207511  0.57355593 -1.41316008  1.20154058  0.06914268
  1.70866355 -1.04638796 -1.42126041  0.32322433  1.57992139 -0.01731771
  0.02002843 -0.31942835 -0.61558767  0.51106504  0.26458136  1.41818785
  0.08558937  0.25701995  0.11328581  0.3105467   1.954388    0.68776003
 -1.04498059  1.63788729  0.88816711  0.90942549  0.08375893 -1.23043595
  0.62310316 -1.92622358 -1.15378894  1.13898297 -0.82291071 -0.28399507
  0.18560517 -0.37321037]
